services:
  backend:
    container_name: link-thru_backend
    build: ./backend
    env_file:
      - .env
      - ./backend/.env
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: link-thru_postgres
    restart: unless-stopped
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:9.6
    container_name: link-thru_pgadmin
    restart: unless-stopped
    env_file:
      - '.env'
      - ./pgAdmin/.env
    ports:
      - '8080:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgAdmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

volumes:
  db_data:
  pgadmin_data:
